{{- /* "chezmoi" is present as work around for https://github.com/twpayne/chezmoi/discussions/1724 */ -}}
{{- $cache := dict "chezmoi" .chezmoi -}}

{{- template "read-versions-and-revisions-cache" $cache -}}

"usr/share/keyrings/google-chrome-archive-keyring.gpg":
  type: file
  url: "https://dl.google.com/linux/linux_signing_key.pub"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/1password-archive-keyring.gpg":
  type: file
  url: "https://downloads.1password.com/linux/keys/1password.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

{{ template "save-versions-and-revisions-cache" $cache -}}
