{{- /* Chezmoi External */ -}}

{{- /* Avoid IDE errors */ -}}

"usr/share/keyrings/docker-archive-keyring.gpg":
  type: file
  url: "https://download.docker.com/linux/{{ .chezmoi.osRelease.id }}/gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/microsoft.gpg":
  type: file
  url: "https://packages.microsoft.com/keys/microsoft.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/google-chrome-archive-keyring.gpg":
  type: file
  url: "https://dl.google.com/linux/linux_signing_key.pub"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/1password-archive-keyring.gpg":
  type: file
  url: "https://downloads.1password.com/linux/keys/1password.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg":
  type: file
  url: "https://downloads.1password.com/linux/keys/1password.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

"etc/debsig/policies/AC2D62742012EA22/1password.pol":
  type: file
  url: "https://downloads.1password.com/linux/debian/debsig/1password.pol"

"usr/share/keyrings/bruno.gpg":
  type: file
  url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x9FA6017ECABE0266"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/sublimehq-archive.gpg":
  type: file
  url: "https://download.sublimetext.com/sublimehq-pub.gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/pipewire-extra-bt-codecs.gpg":
  type: file
  url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x018608be284ad8ee9e90e44ce265bd42d7e7e88c"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/stripe.gpg":
  type: file
  url: "https://packages.stripe.dev/api/security/keypair/stripe-cli-gpg/public"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/httpie.gpg":
  type: file
  url: "https://packages.httpie.io/deb/KEY.gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/postgresql.gpg":
  type: file
  url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/mise-archive-keyring.gpg":
  type: file
  url: "https://mise.jdx.dev/gpg-key.pub"
  filter:
    command: gpg
    args: ["--dearmor"]

{{ $dockerCredentialSecretServiceVersion := includeTemplate "get-github-latest-version" "docker/docker-credential-helpers" }}
"usr/bin/docker-credential-secretservice":
  type: file
  url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ $dockerCredentialSecretServiceVersion }}/docker-credential-secretservice-v{{ $dockerCredentialSecretServiceVersion }}.{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
  executable: true
