{{- /* "chezmoi" is present as work around for https://github.com/twpayne/chezmoi/discussions/1724 */ -}}
{{- $cache := dict "chezmoi" .chezmoi -}}

{{- template "read-versions-and-revisions-cache" $cache -}}

"usr/share/keyrings/docker-archive-keyring.gpg":
  type: file
  url: "https://download.docker.com/linux/{{ .chezmoi.osRelease.id }}/gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/vscode-archive-keyring.gpg":
  type: file
  url: "https://packages.microsoft.com/keys/microsoft.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/google-chrome-archive-keyring.gpg":
  type: file
  url: "https://dl.google.com/linux/linux_signing_key.pub"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/1password-archive-keyring.gpg":
  type: file
  url: "https://downloads.1password.com/linux/keys/1password.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg":
  type: file
  url: "https://downloads.1password.com/linux/keys/1password.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

"etc/debsig/policies/AC2D62742012EA22/1password.pol":
  type: file
  url: "https://downloads.1password.com/linux/debian/debsig/1password.pol"

"usr/share/keyrings/sublimehq-archive.gpg":
  type: file
  url: "https://download.sublimetext.com/sublimehq-pub.gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/spotify.gpg":
  type: file
  url: "https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/pipewire-extra-bt-codecs.gpg":
  type: file
  url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x018608be284ad8ee9e90e44ce265bd42d7e7e88c"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/stripe.gpg":
  type: file
  url: "https://packages.stripe.dev/api/security/keypair/stripe-cli-gpg/public"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/httpie.gpg":
  type: file
  url: "https://packages.httpie.io/deb/KEY.gpg"
  filter:
    command: gpg
    args: ["--dearmor"]

"usr/share/keyrings/postgresql.gpg":
  type: file
  url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
  filter:
    command: gpg
    args: ["--dearmor"]

{{ $dockerCredentialSecretserviceVersion := includeTemplate "get-github-latest-version" (list "docker/docker-credential-helpers" $cache) }}
"usr/bin/docker-credential-secretservice":
  type: file
  url: "https://github.com/docker/docker-credential-helpers/releases/download/v{{ $dockerCredentialSecretserviceVersion }}/docker-credential-secretservice-v{{ $dockerCredentialSecretserviceVersion }}.{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
  executable: true

{{ template "save-versions-and-revisions-cache" $cache -}}
