#!/usr/bin/env bash

# `aliases` is used to provide custom variables.
#
# This file is used as a part of `.shell-env`


# === Aliases ===

# kubecolor
alias kubectl="kubecolor"
# make completion work with kubecolor
compdef kubecolor=kubectl
